name: PostMaster

services:
  django-dev:
    image: django-dev
    ports:
      - 8000:8000
    networks:
      - back-tier
    volumes:
      - ../PostMasterDjango:/app
    depends_on:
      - mariadb
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: sh -c "gunicorn postmasterdjango.wsgi:application -b 0.0.0.0:8000 --reload"
    # command: sh -c "gunicorn postmasterdjango.wsgi:application -b 0.0.0.0:8000"
    # --reload option is only for development, remove it for production
  react-dev:
    image: react-dev
    ports:
      - 3000:3000
    networks:
      - front-tier
    volumes:
      - ../PostMasterReact/postmasterreact:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    # command: sh -c "npm install && npm start"
  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - front-tier
      - back-tier
    depends_on:
      - django-dev
    volumes:
      - ../PostMasterReact/postmasterreact/dist:/usr/share/nginx/html
      - ../../Common/Documentation/documentation/site:/usr/share/nginx/documentation
      - ./dev-nginx.conf:/etc/nginx/conf.d/default.conf:ro
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - back-tier
  mkdocs:
    image: mkdocs
    ports:
      - 9000:9000
    networks:
      - front-tier
    volumes:
      - ../../Common/Documentation/documentation:/app
    command: mkdocs serve -a 0.0.0.0:9000

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
    # internal: true # Bu değer production'da mutlaka uncomment yapılmalı.